# Generated by Django 5.0.6 on 2024-06-22 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="manufactured_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=(11, 11, 2022),
                verbose_name="дата производства продукта",
            ),
            preserve_default=False,
        ),
    ]
